name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Build with Maven
      run: mvn compile
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3